import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';
import { apiGet, apiPost, getApiStatus } from './api';

const modules = ['Dashboard','Power Partners','Contacts','Touchpoints','Operations','Expenses','Surveys','Settings'];
const fallbackContacts = [{ Company: 'Tomei Insurance Agency', First_Name: 'Tomei', Last_Name: 'Agency', Vertical: 'Insurance', Market: 'Gurnee', Email: '', Status: 'Priority Invite', Cluster: 'Insurance & Escalation' },{ Company: "West's Insurance Agency", First_Name: 'West', Last_Name: 'Agency', Vertical: 'Insurance', Market: 'Gurnee', Email: '', Status: 'Priority Invite', Cluster: 'Commercial Property' },{ Company: 'Michael Logue Insurance', First_Name: 'Michael', Last_Name: 'Logue', Vertical: 'Insurance', Market: 'Gurnee', Email: '', Status: 'Invite Ready', Cluster: 'Residential Referral' }];

function App() {
  const [activeTab, setActiveTab] = useState('Dashboard');
  const [metrics, setMetrics] = useState({ contacts: 0, invites: 0, rsvps: 0, touchpoints: 0, opsRequests: 0, expenses: 0 });
  const [contacts, setContacts] = useState(fallbackContacts);
  const [activity, setActivity] = useState(['Platform loaded', 'Google Sheet API ready']);
  const [apiMessage, setApiMessage] = useState('');
  const [showContactModal, setShowContactModal] = useState(false);
  const [contactForm, setContactForm] = useState({ First_Name: '', Last_Name: '', Company: '', Title: '', Vertical: 'Insurance', Market: 'Gurnee', Email: '', Phone: '', Priority: 'High', Cluster: 'Power Partners Weekly', Owner: 'Brandon Bynum', Status: 'New' });
  const [touchpoint, setTouchpoint] = useState({ Contact_Company: '', Vertical: 'Insurance', Market: 'Gurnee', Touchpoint_Type: 'Email', Pipeline_Stage: 'Engaged', Outcome: '', Next_Step: '' });
  const [opsForm, setOpsForm] = useState({ Submitted_By: 'Brandon Bynum', Request_Type: 'Operations Support', Related_Contact_Company: '', Priority: 'Medium', Needed_By: '', Assigned_To: 'Dan', Status: 'Open', Notes: '' });
  const [expenseForm, setExpenseForm] = useState({ BDM: 'Brandon Bynum', Expense_Date: '', Vendor: '', Category: 'Meal / Coffee', Amount: '', Business_Purpose: '', Related_Contact_Event: '', Submitted_To: 'Joy', Notes: '' });
  const [surveyForm, setSurveyForm] = useState({ Event_Session: 'Power Partners Weekly', Guest_Name: '', Company: '', Email: '', Rating: '5', Best_Part: '', Referral_Interest: 'Yes', Follow_Up_Requested: 'Yes', Testimonial_Permission: 'No', Google_Review_Requested: 'No', Notes: '' });

  const statCards = useMemo(() => [['Contacts', metrics.contacts || contacts.length, 'live relationship database'],['Invites Sent', metrics.invites || 0, 'Power Partners outreach'],['RSVPs', metrics.rsvps || 0, 'confirmed or pending'],['Touchpoints', metrics.touchpoints || 0, 'BDM activity'],['Ops Requests', metrics.opsRequests || 0, 'internal support'],['Expenses', metrics.expenses || 0, 'approval queue']], [metrics, contacts.length]);

  async function refreshDashboard() { const dashboard = await apiGet('dashboard'); if (dashboard && dashboard.ok) setMetrics(dashboard); const liveContacts = await apiGet('contacts'); if (Array.isArray(liveContacts) && liveContacts.length) setContacts(liveContacts); setActivity(prev => ['Dashboard refreshed from Google Sheet', ...prev].slice(0, 8)); }
  useEffect(() => { refreshDashboard(); }, []);
  async function addContact() { const result = await apiPost('addContact', contactForm); setApiMessage(result.ok ? 'Contact submitted to Google Sheet.' : 'Contact staged. Check Apps Script access.'); setActivity(prev => [`Contact added: ${contactForm.Company}`, ...prev].slice(0, 8)); setContacts(prev => [contactForm, ...prev]); setShowContactModal(false); }
  async function logTouchpoint() { const payload = { BDM: 'Brandon Bynum', ...touchpoint, Qualifying_Touchpoint: 'TRUE', Revenue_Opportunity: '', Notes: 'Logged from dashboard' }; const result = await apiPost('logTouchpoint', payload); setApiMessage(result.ok ? 'Touchpoint submitted to Google Sheet.' : 'Touchpoint staged. Check Apps Script access.'); setActivity(prev => [`Touchpoint logged: ${touchpoint.Contact_Company}`, ...prev].slice(0, 8)); setTouchpoint({ ...touchpoint, Contact_Company: '', Outcome: '', Next_Step: '' }); }
  async function sendInvite(contact) { const result = await apiPost('sendInvite', { Contact_Name: `${contact.First_Name || ''} ${contact.Last_Name || ''}`.trim() || contact.Company, Email: contact.Email, Contact_Company: contact.Company, Owner: 'Brandon Bynum', Cluster: contact.Cluster || 'Power Partners Weekly' }); setApiMessage(result.ok ? `Invite workflow submitted for ${contact.Company}.` : `Invite staged for ${contact.Company}.`); setActivity(prev => [`Invite action: ${contact.Company}`, ...prev].slice(0, 8)); }
  async function submitOps() { const result = await apiPost('logOperationsRequest', opsForm); setApiMessage(result.ok ? 'Operations request submitted.' : 'Operations request staged.'); setActivity(prev => [`Ops request: ${opsForm.Related_Contact_Company || opsForm.Request_Type}`, ...prev].slice(0, 8)); }
  async function submitExpense() { const result = await apiPost('logExpense', expenseForm); setApiMessage(result.ok ? 'Expense submitted to Joy queue.' : 'Expense staged.'); setActivity(prev => [`Expense submitted: ${expenseForm.Vendor}`, ...prev].slice(0, 8)); }
  async function submitSurvey() { const result = await apiPost('logSurvey', surveyForm); setApiMessage(result.ok ? 'Survey response submitted.' : 'Survey response staged.'); setActivity(prev => [`Survey logged: ${surveyForm.Guest_Name}`, ...prev].slice(0, 8)); }

  function Header() { return <><section className="hero"><div><span className="eyebrow">{activeTab}</span><h2>SMKR Power Partner Command Center</h2><p>Live workspace for outreach, referral rooms, contacts, touchpoints, operations, expenses, surveys, and BDM KPI visibility.</p></div><div className="hero-actions"><a href="https://genuine-flan-635798.netlify.app/" target="_blank" rel="noreferrer">View RSVP Page</a><button onClick={refreshDashboard}>Refresh Live Data</button></div></section>{apiMessage && <section className="api-banner">{apiMessage}</section>}</>; }

  function Dashboard() { return <><section className="stats-grid">{statCards.map(([label, value, note]) => <article className="stat-card" key={label}><span>{label}</span><strong>{value}</strong><p>{note}</p></article>)}</section><section className="two-column"><article className="panel dark-panel"><span className="eyebrow yellow">BDM KPI Tracking</span><h3>Weekly Power Partner Motion</h3><p>Track founding seats, invite actions, touchpoints, and operational queues.</p><div className="room-grid"><div><span>Target Seats</span><strong>8</strong></div><div><span>Active Contacts</span><strong>{contacts.length}</strong></div><div><span>Touchpoints</span><strong>{metrics.touchpoints || 0}</strong></div></div></article><Activity /></section></>; }
  function Activity() { return <article className="panel"><span className="eyebrow">Real-Time Activity Feed</span><h3>Latest Platform Actions</h3><ul className="task-list">{activity.map((item, idx) => <li key={idx}>{item}</li>)}</ul></article>; }
  function Contacts() { return <section className="panel"><div className="section-header"><div><span className="eyebrow">Live Contact Table</span><h3>Power Partner Contact Database</h3></div><button onClick={() => setShowContactModal(true)}>Add Contact</button></div><div className="table-wrap"><table><thead><tr><th>Company</th><th>Name</th><th>Vertical</th><th>Market</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{contacts.map((c, idx) => <tr key={`${c.Company}-${idx}`}><td>{c.Company}</td><td>{`${c.First_Name || ''} ${c.Last_Name || ''}`}</td><td>{c.Vertical}</td><td>{c.Market}</td><td>{c.Email}</td><td><span className="pill">{c.Status || 'Active'}</span></td><td><button className="small" onClick={() => sendInvite(c)}>Invite</button></td></tr>)}</tbody></table></div></section>; }
  function PowerPartners() { return <><section className="two-column"><article className="panel dark-panel"><span className="eyebrow yellow">Power Partners Weekly</span><h3>Room Builder</h3><p>Wednesday · 8:00-9:00 AM · ServiceMaster KWIK Restore HQ, Gurnee</p><div className="room-grid"><div><span>Target Size</span><strong>8</strong></div><div><span>Open Seats</span><strong>{Math.max(8 - contacts.length, 0)}</strong></div><div><span>Invites</span><strong>{metrics.invites || 0}</strong></div></div><button onClick={() => setActiveTab('Contacts')}>Build Invite List</button></article><Activity /></section><Contacts /></>; }
  function Touchpoints() { return <><section className="panel"><span className="eyebrow">Live Touchpoint Logger</span><h3>BDM Touchpoint</h3><div className="form-grid"><input value={touchpoint.Contact_Company} onChange={e => setTouchpoint({...touchpoint, Contact_Company: e.target.value})} placeholder="Contact / Company" /><select value={touchpoint.Touchpoint_Type} onChange={e => setTouchpoint({...touchpoint, Touchpoint_Type: e.target.value})}><option>Email</option><option>Call</option><option>In-Person</option><option>LinkedIn</option><option>Lunch & Learn</option></select><select value={touchpoint.Pipeline_Stage} onChange={e => setTouchpoint({...touchpoint, Pipeline_Stage: e.target.value})}><option>Prospect</option><option>Engaged</option><option>Evaluating</option><option>Partner</option></select><button onClick={logTouchpoint}>Log</button></div></section><section className="three-column lower"><article className="panel mini"><span className="eyebrow">Touchpoint History</span><strong>{metrics.touchpoints || 0}</strong><p>Total logged actions.</p></article><article className="panel mini"><span className="eyebrow">Primary Motion</span><strong>BDM</strong><p>Relationship building.</p></article><article className="panel mini"><span className="eyebrow">Pipeline</span><strong>Engaged</strong><p>Current default stage.</p></article></section></>; }
  function Operations() { return <section className="panel"><span className="eyebrow">Operations Request Queue</span><h3>Submit Operations Request</h3><div className="modal-grid"><input placeholder="Related Company" value={opsForm.Related_Contact_Company} onChange={e => setOpsForm({...opsForm, Related_Contact_Company: e.target.value})} /><select value={opsForm.Priority} onChange={e => setOpsForm({...opsForm, Priority: e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select><input placeholder="Needed By" value={opsForm.Needed_By} onChange={e => setOpsForm({...opsForm, Needed_By: e.target.value})} /><input placeholder="Notes" value={opsForm.Notes} onChange={e => setOpsForm({...opsForm, Notes: e.target.value})} /></div><button onClick={submitOps}>Submit Request</button></section>; }
  function Expenses() { return <section className="panel"><span className="eyebrow">Expense Approval Queue</span><h3>Submit Expense</h3><div className="modal-grid"><input placeholder="Vendor" value={expenseForm.Vendor} onChange={e => setExpenseForm({...expenseForm, Vendor: e.target.value})} /><input placeholder="Amount" value={expenseForm.Amount} onChange={e => setExpenseForm({...expenseForm, Amount: e.target.value})} /><input placeholder="Business Purpose" value={expenseForm.Business_Purpose} onChange={e => setExpenseForm({...expenseForm, Business_Purpose: e.target.value})} /><input placeholder="Related Event" value={expenseForm.Related_Contact_Event} onChange={e => setExpenseForm({...expenseForm, Related_Contact_Event: e.target.value})} /></div><button onClick={submitExpense}>Submit Expense</button></section>; }
  function Surveys() { return <section className="panel"><span className="eyebrow">Survey Response Viewer</span><h3>Log Guest Feedback</h3><div className="modal-grid"><input placeholder="Guest Name" value={surveyForm.Guest_Name} onChange={e => setSurveyForm({...surveyForm, Guest_Name: e.target.value})} /><input placeholder="Company" value={surveyForm.Company} onChange={e => setSurveyForm({...surveyForm, Company: e.target.value})} /><input placeholder="Email" value={surveyForm.Email} onChange={e => setSurveyForm({...surveyForm, Email: e.target.value})} /><input placeholder="Best Part" value={surveyForm.Best_Part} onChange={e => setSurveyForm({...surveyForm, Best_Part: e.target.value})} /></div><button onClick={submitSurvey}>Submit Survey</button></section>; }
  function Settings() { return <section className="panel"><span className="eyebrow">Settings</span><h3>System Configuration</h3><div className="ops-list"><div><span>API Status</span><strong>{getApiStatus()}</strong></div><div><span>Database</span><strong>Google Sheets</strong></div><div><span>Owner</span><strong>Brandon</strong></div></div></section>; }
  function ActiveView() { if (activeTab === 'Power Partners') return <PowerPartners />; if (activeTab === 'Contacts') return <Contacts />; if (activeTab === 'Touchpoints') return <Touchpoints />; if (activeTab === 'Operations') return <Operations />; if (activeTab === 'Expenses') return <Expenses />; if (activeTab === 'Surveys') return <Surveys />; if (activeTab === 'Settings') return <Settings />; return <Dashboard />; }

  return <div className="platform"><aside className="sidebar"><div className="brand-lockup"><div className="brand-mark">SMKR</div><h1>Power Partner Platform</h1><p>Outreach · Referrals · Metrics · Operations</p></div><nav>{modules.map(item => <button onClick={() => setActiveTab(item)} className={activeTab === item ? 'nav-active' : ''} key={item}>{item}</button>)}</nav><div className="sidebar-footer"><strong>Found. Chosen. Remembered.</strong><span>Gurnee & Cary, Illinois</span><small>{getApiStatus()}</small></div></aside><main className="workspace"><Header /><ActiveView /></main>{showContactModal && <div className="modal-backdrop"><div className="modal"><div className="section-header"><div><span className="eyebrow">Add Contact</span><h3>New Power Partner Contact</h3></div><button className="small" onClick={() => setShowContactModal(false)}>Close</button></div><div className="modal-grid"><input placeholder="First Name" value={contactForm.First_Name} onChange={e => setContactForm({...contactForm, First_Name: e.target.value})} /><input placeholder="Last Name" value={contactForm.Last_Name} onChange={e => setContactForm({...contactForm, Last_Name: e.target.value})} /><input placeholder="Company" value={contactForm.Company} onChange={e => setContactForm({...contactForm, Company: e.target.value})} /><input placeholder="Title" value={contactForm.Title} onChange={e => setContactForm({...contactForm, Title: e.target.value})} /><input placeholder="Email" value={contactForm.Email} onChange={e => setContactForm({...contactForm, Email: e.target.value})} /><input placeholder="Phone" value={contactForm.Phone} onChange={e => setContactForm({...contactForm, Phone: e.target.value})} /><select value={contactForm.Vertical} onChange={e => setContactForm({...contactForm, Vertical: e.target.value})}><option>Insurance</option><option>Real Estate</option><option>Commercial Broker</option><option>Property Management</option><option>Mortgage</option><option>Home Care</option></select><input placeholder="Market" value={contactForm.Market} onChange={e => setContactForm({...contactForm, Market: e.target.value})} /></div><button onClick={addContact}>Save Contact to Sheet</button></div></div>}</div>;
}

ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);
