import React, { useEffect, useMemo, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './styles.css';
import { apiGet, apiPost, getApiStatus } from './api';

const modules = ['Dashboard','Import','Contacts','Touchpoints','Operations','Expenses','Surveys','Settings'];
const importPreview = [
  {First_Name:'Hal',Last_Name:'Baker',Company:'Goosehead Insurance-Hal Baker',Vertical:'Insurance',Market:'Barrington IL',Email:'hal.baker@goosehead.com',Phone:'1 (847) 276-2717',Class_Tier:'B2',Referral_History:'34 all-time refs | $166,958.85',Relationship_Score:88,Source_Workbook:'POWER PARTNERS - ALL CONTACTS.xlsx',Source_Sheet:'Brandon Bynum — Contacts',Owner:'Brandon Bynum'},
  {First_Name:'Shannon',Last_Name:'Morreale',Company:'State Farm Insurance-Shannon Morreale',Vertical:'Insurance',Market:'Cary IL',Email:'shannon.morreale.k0v6@statefarm.com',Phone:'1 (847) 639-2828',Class_Tier:'B2',Referral_History:'14 all-time refs | $138,074.88',Relationship_Score:84,Source_Workbook:'POWER PARTNERS - ALL CONTACTS.xlsx',Source_Sheet:'Brandon Bynum — Contacts',Owner:'Brandon Bynum'},
  {First_Name:'Phil',Last_Name:'Horn',Company:'State Farm Insurance-Phil Horn',Vertical:'Insurance',Market:'Cary IL',Email:'phil.horn.m2h3@statefarm.com',Phone:'1 (847) 639-9467',Class_Tier:'B2',Referral_History:'7 all-time refs | $128,808.80',Relationship_Score:80,Source_Workbook:'POWER PARTNERS - ALL CONTACTS.xlsx',Source_Sheet:'Brandon Bynum — Contacts',Owner:'Brandon Bynum'},
  {First_Name:'Alicia',Last_Name:'Rodriguez',Company:'American Family Insurance-Alicia Rodriguez',Vertical:'Insurance',Market:'Waukegan IL',Email:'arodrig7@amfam.com',Phone:'1 (847) 244-8870',Class_Tier:'B2',Referral_History:'2 all-time refs | $65,784.17',Relationship_Score:74,Source_Workbook:'POWER PARTNERS - ALL CONTACTS.xlsx',Source_Sheet:'Brandon Bynum — Contacts',Owner:'Brandon Bynum'},
  {First_Name:'Kim',Last_Name:'Menheer',Company:'Assured Healthcare Staffing',Vertical:'Home Care / Healthcare',Market:'Gurnee IL',Email:'kim@assuredhealthcare.com',Phone:'(847) 775-7445',Class_Tier:'A3',Referral_History:'1 all-time ref | $3,393.00',Relationship_Score:72,Source_Workbook:'POWER PARTNERS - ALL CONTACTS.xlsx',Source_Sheet:'Brandon Bynum — Contacts',Owner:'Brandon Bynum'}
];
function App(){
 const [activeTab,setActiveTab]=useState('Dashboard'); const [metrics,setMetrics]=useState({contacts:0,invites:0,rsvps:0,touchpoints:0,opsRequests:0,expenses:0}); const [contacts,setContacts]=useState([]); const [lastSynced,setLastSynced]=useState('Not synced yet'); const [activity,setActivity]=useState(['V2.6 Import + Receipt Infrastructure loaded','Awaiting live Google Sheet records']); const [apiMessage,setApiMessage]=useState(''); const [showContactModal,setShowContactModal]=useState(false);
 const [contactForm,setContactForm]=useState({First_Name:'',Last_Name:'',Company:'',Title:'',Vertical:'Insurance',Market:'Gurnee',Email:'',Phone:'',Priority:'High',Cluster:'Power Partners Weekly',Owner:'Brandon Bynum',Status:'New'});
 const [touchpoint,setTouchpoint]=useState({Contact_Company:'',Vertical:'Insurance',Market:'Gurnee',Touchpoint_Type:'Email',Pipeline_Stage:'Engaged',Outcome:'',Next_Step:''});
 const [opsForm,setOpsForm]=useState({Submitted_By:'Brandon Bynum',Request_Type:'Operations Support',Related_Contact_Company:'',Priority:'Medium',Needed_By:'',Assigned_To:'Dan',Status:'Open',Notes:''});
 const [expenseForm,setExpenseForm]=useState({BDM:'Brandon Bynum',Expense_Date:'',Vendor:'',Category:'Meal / Coffee',Amount:'',Business_Purpose:'',Related_Contact_Event:'',Receipt_Link:'',Receipt_File_Name:'',Receipt_Upload_Status:'Pending Link',Submitted_To:'Joy',Approval_Status:'Submitted',Notes:''});
 const [surveyForm,setSurveyForm]=useState({Event_Session:'Power Partners Weekly',Guest_Name:'',Company:'',Email:'',Rating:'5',Best_Part:'',Referral_Interest:'Yes',Follow_Up_Requested:'Yes',Testimonial_Permission:'No',Google_Review_Requested:'No',Notes:''});
 const liveContactCount=contacts.length; const statCards=useMemo(()=>[['Contacts',liveContactCount,'live Contacts tab records'],['Import Preview',importPreview.length,'curated Brandon-owned records'],['Invites Sent',metrics.invites||0,'Invite_Log tab records'],['Touchpoints',metrics.touchpoints||0,'Touchpoints tab records'],['Ops Requests',metrics.opsRequests||0,'Operations_Requests tab records'],['Expenses',metrics.expenses||0,'Expenses tab records']], [metrics,liveContactCount]);
 async function refreshDashboard(){const dashboard=await apiGet('dashboard');const liveContacts=await apiGet('contacts');const next=Array.isArray(liveContacts)?liveContacts:[];setContacts(next);setMetrics({contacts:next.length,invites:dashboard&&dashboard.ok?dashboard.invites||0:0,rsvps:dashboard&&dashboard.ok?dashboard.rsvps||0:0,touchpoints:dashboard&&dashboard.ok?dashboard.touchpoints||0:0,opsRequests:dashboard&&dashboard.ok?dashboard.opsRequests||0:0,expenses:dashboard&&dashboard.ok?dashboard.expenses||0:0});setLastSynced(new Date().toLocaleString());setActivity(p=>[`Relationship Database synced: ${next.length} live contact record(s)`,...p].slice(0,8));}
 useEffect(()=>{refreshDashboard();},[]);
 async function addContact(data=contactForm){const result=await apiPost('addContact',data);setApiMessage(result.ok?'Contact submitted to Google Sheet. Refresh live data to confirm.':'Contact staged. Check Apps Script access.');setActivity(p=>[`Contact submitted: ${data.Company}`,...p].slice(0,8));setShowContactModal(false);await refreshDashboard();}
 async function importRecord(r){await addContact({First_Name:r.First_Name,Last_Name:r.Last_Name,Company:r.Company,Title:'',Vertical:r.Vertical,Market:r.Market,Email:r.Email,Phone:r.Phone,Priority:r.Relationship_Score>=80?'High':'Medium',Cluster:'Insurance & Escalation',Source:r.Source_Workbook,Owner:r.Owner,Status:'Imported',Notes:`${r.Class_Tier} | ${r.Referral_History} | Score ${r.Relationship_Score} | Source sheet ${r.Source_Sheet}`});}
 async function logTouchpoint(){const result=await apiPost('logTouchpoint',{BDM:'Brandon Bynum',...touchpoint,Qualifying_Touchpoint:'TRUE',Notes:'Logged from dashboard'});setApiMessage(result.ok?'Touchpoint submitted to Google Sheet.':'Touchpoint staged.');setActivity(p=>[`Touchpoint logged: ${touchpoint.Contact_Company}`,...p].slice(0,8));await refreshDashboard();}
 async function sendInvite(c){const result=await apiPost('sendInvite',{Contact_Name:`${c.First_Name||''} ${c.Last_Name||''}`.trim()||c.Company,Email:c.Email,Contact_Company:c.Company,Owner:'Brandon Bynum',Cluster:c.Cluster||'Power Partners Weekly'});setApiMessage(result.ok?`Invite workflow submitted for ${c.Company}.`:`Invite staged for ${c.Company}.`);await refreshDashboard();}
 async function submitOps(){const result=await apiPost('logOperationsRequest',opsForm);setApiMessage(result.ok?'Operations request submitted.':'Operations request staged.');await refreshDashboard();}
 async function submitExpense(){const result=await apiPost('logExpense',expenseForm);setApiMessage(result.ok?'Expense submitted to Joy queue with receipt fields.':'Expense staged.');setActivity(p=>[`Expense submitted: ${expenseForm.Vendor} | Receipt: ${expenseForm.Receipt_Upload_Status}`,...p].slice(0,8));await refreshDashboard();}
 async function submitSurvey(){const result=await apiPost('logSurvey',surveyForm);setApiMessage(result.ok?'Survey response submitted.':'Survey response staged.');await refreshDashboard();}
 function Header(){return <><section className="hero"><div><span className="eyebrow">{activeTab}</span><h2>SMKR Power Partner Command Center</h2><p>V2.6 adds staged master import, source visibility, Luxor classification mapping, relationship scoring, and expense receipt link tracking.</p></div><div className="hero-actions"><a href="https://docs.google.com/spreadsheets/d/1qeOi2XoYc_9GEh_3R70osM4KrO8s_29j_kHhmyoZBtY/edit?usp=sharing" target="_blank" rel="noreferrer">Open Database</a><button onClick={refreshDashboard}>Refresh Live Data</button></div></section>{apiMessage&&<section className="api-banner">{apiMessage}</section>}</>}
 function Dashboard(){return <><section className="stats-grid">{statCards.map(([l,v,n])=><article className="stat-card" key={l}><span>{l}</span><strong>{v}</strong><p>{n}</p></article>)}</section><section className="two-column"><article className="panel dark-panel"><span className="eyebrow yellow">Relationship Database</span><h3>Live Source of Truth</h3><p>Source: Contacts tab. Last synced: {lastSynced}. No demo contacts are counted.</p><div className="room-grid"><div><span>Live Contacts</span><strong>{liveContactCount}</strong></div><div><span>Import Preview</span><strong>{importPreview.length}</strong></div><div><span>Receipt Fields</span><strong>Ready</strong></div></div></article><Activity/></section></>}
 function Activity(){return <article className="panel"><span className="eyebrow">Real-Time Activity Feed</span><h3>Latest Platform Actions</h3><ul className="task-list">{activity.map((i,x)=><li key={x}>{i}</li>)}</ul></article>}
 function Import(){return <section className="panel"><div className="section-header"><div><span className="eyebrow">Master Import Workflow</span><h3>Curated Brandon-Owned Import Preview</h3><p className="helper-text">Dedupe key: Email first, then Company. Records preserve source workbook, source sheet, class/tier, referral history, owner, and imported date in Notes/Source fields.</p></div><button onClick={()=>setApiMessage('Import mode is staged one-record-at-a-time to avoid large batch failures.')}>Safe Import Mode</button></div><div className="table-wrap"><table><thead><tr><th>Score</th><th>Contact</th><th>Company</th><th>Tier</th><th>Referral History</th><th>Source</th><th>Action</th></tr></thead><tbody>{importPreview.map(r=><tr key={r.Company}><td><span className="pill">{r.Relationship_Score}</span></td><td>{r.First_Name} {r.Last_Name}</td><td>{r.Company}</td><td>{r.Class_Tier}</td><td>{r.Referral_History}</td><td>{r.Source_Sheet}</td><td><button className="small" onClick={()=>importRecord(r)}>Import</button></td></tr>)}</tbody></table></div></section>}
 function EmptyContacts(){return <div className="empty-state"><h3>No live relationship records yet.</h3><p>Add a contact or import curated records from the Import tab.</p><button onClick={()=>setActiveTab('Import')}>Open Import Preview</button></div>}
 function Contacts(){return <section className="panel"><div className="section-header"><div><span className="eyebrow">Relationship Database</span><h3>Live Contacts Tab Records</h3><p className="helper-text">Source: Google Sheets → Contacts. Live records: {liveContactCount}. Last synced: {lastSynced}.</p></div><button onClick={()=>setShowContactModal(true)}>Add Contact</button></div>{contacts.length===0?<EmptyContacts/>:<div className="table-wrap"><table><thead><tr><th>Company</th><th>Name</th><th>Vertical</th><th>Market</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{contacts.map((c,i)=><tr key={`${c.Company}-${i}`}><td>{c.Company}</td><td>{`${c.First_Name||''} ${c.Last_Name||''}`}</td><td>{c.Vertical}</td><td>{c.Market}</td><td>{c.Email}</td><td><span className="pill">{c.Status||'Active'}</span></td><td><button className="small" onClick={()=>sendInvite(c)}>Invite</button></td></tr>)}</tbody></table></div>}</section>}
 function Touchpoints(){return <section className="panel"><span className="eyebrow">Live Touchpoint Logger</span><h3>BDM Touchpoint</h3><div className="form-grid"><input value={touchpoint.Contact_Company} onChange={e=>setTouchpoint({...touchpoint,Contact_Company:e.target.value})} placeholder="Contact / Company"/><select value={touchpoint.Touchpoint_Type} onChange={e=>setTouchpoint({...touchpoint,Touchpoint_Type:e.target.value})}><option>Email</option><option>Call</option><option>In-Person</option><option>LinkedIn</option><option>Lunch & Learn</option></select><select value={touchpoint.Pipeline_Stage} onChange={e=>setTouchpoint({...touchpoint,Pipeline_Stage:e.target.value})}><option>Prospect</option><option>Engaged</option><option>Evaluating</option><option>Partner</option></select><button onClick={logTouchpoint}>Log</button></div></section>}
 function Operations(){return <section className="panel"><span className="eyebrow">Operations Request Queue</span><h3>Submit Operations Request</h3><div className="modal-grid"><input placeholder="Related Company" value={opsForm.Related_Contact_Company} onChange={e=>setOpsForm({...opsForm,Related_Contact_Company:e.target.value})}/><select value={opsForm.Priority} onChange={e=>setOpsForm({...opsForm,Priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select><input placeholder="Needed By" value={opsForm.Needed_By} onChange={e=>setOpsForm({...opsForm,Needed_By:e.target.value})}/><input placeholder="Notes" value={opsForm.Notes} onChange={e=>setOpsForm({...opsForm,Notes:e.target.value})}/></div><button onClick={submitOps}>Submit Request</button></section>}
 function Expenses(){return <section className="panel"><span className="eyebrow">Expense Receipt Workflow</span><h3>Submit Expense to Joy Queue</h3><p className="helper-text">Upload receipt to Google Drive, then paste the share link here. The platform stores receipt link, file name, upload status, and approval status.</p><div className="modal-grid"><input placeholder="Vendor" value={expenseForm.Vendor} onChange={e=>setExpenseForm({...expenseForm,Vendor:e.target.value})}/><input placeholder="Amount" value={expenseForm.Amount} onChange={e=>setExpenseForm({...expenseForm,Amount:e.target.value})}/><input placeholder="Receipt Drive Link" value={expenseForm.Receipt_Link} onChange={e=>setExpenseForm({...expenseForm,Receipt_Link:e.target.value,Receipt_Upload_Status:e.target.value?'Linked':'Pending Link'})}/><input placeholder="Receipt File Name" value={expenseForm.Receipt_File_Name} onChange={e=>setExpenseForm({...expenseForm,Receipt_File_Name:e.target.value})}/><input placeholder="Business Purpose" value={expenseForm.Business_Purpose} onChange={e=>setExpenseForm({...expenseForm,Business_Purpose:e.target.value})}/><input placeholder="Related Event" value={expenseForm.Related_Contact_Event} onChange={e=>setExpenseForm({...expenseForm,Related_Contact_Event:e.target.value})}/></div><button onClick={submitExpense}>Submit Expense + Receipt Link</button></section>}
 function Surveys(){return <section className="panel"><span className="eyebrow">Survey Response Viewer</span><h3>Log Guest Feedback</h3><div className="modal-grid"><input placeholder="Guest Name" value={surveyForm.Guest_Name} onChange={e=>setSurveyForm({...surveyForm,Guest_Name:e.target.value})}/><input placeholder="Company" value={surveyForm.Company} onChange={e=>setSurveyForm({...surveyForm,Company:e.target.value})}/><input placeholder="Email" value={surveyForm.Email} onChange={e=>setSurveyForm({...surveyForm,Email:e.target.value})}/><input placeholder="Best Part" value={surveyForm.Best_Part} onChange={e=>setSurveyForm({...surveyForm,Best_Part:e.target.value})}/></div><button onClick={submitSurvey}>Submit Survey</button></section>}
 function Settings(){return <section className="panel"><span className="eyebrow">Settings</span><h3>System Configuration</h3><div className="ops-list"><div><span>API Status</span><strong>{getApiStatus()}</strong></div><div><span>Relationship Database</span><strong>Contacts Tab</strong></div><div><span>Import Source</span><strong>POWER PARTNERS</strong></div></div></section>}
 function ActiveView(){if(activeTab==='Import')return <Import/>; if(activeTab==='Contacts')return <Contacts/>; if(activeTab==='Touchpoints')return <Touchpoints/>; if(activeTab==='Operations')return <Operations/>; if(activeTab==='Expenses')return <Expenses/>; if(activeTab==='Surveys')return <Surveys/>; if(activeTab==='Settings')return <Settings/>; return <Dashboard/>}
 return <div className="platform"><aside className="sidebar"><div className="brand-lockup"><div className="brand-mark">SMKR</div><h1>Power Partner Platform</h1><p>Outreach · Referrals · Metrics · Operations</p></div><nav>{modules.map(item=><button onClick={()=>setActiveTab(item)} className={activeTab===item?'nav-active':''} key={item}>{item}</button>)}</nav><div className="sidebar-footer"><strong>Found. Chosen. Remembered.</strong><span>Gurnee & Cary, Illinois</span><small>{getApiStatus()}</small></div></aside><main className="workspace"><Header/><ActiveView/></main>{showContactModal&&<div className="modal-backdrop"><div className="modal"><div className="section-header"><div><span className="eyebrow">Add Contact</span><h3>New Relationship Database Record</h3></div><button className="small" onClick={()=>setShowContactModal(false)}>Close</button></div><div className="modal-grid"><input placeholder="First Name" value={contactForm.First_Name} onChange={e=>setContactForm({...contactForm,First_Name:e.target.value})}/><input placeholder="Last Name" value={contactForm.Last_Name} onChange={e=>setContactForm({...contactForm,Last_Name:e.target.value})}/><input placeholder="Company" value={contactForm.Company} onChange={e=>setContactForm({...contactForm,Company:e.target.value})}/><input placeholder="Title" value={contactForm.Title} onChange={e=>setContactForm({...contactForm,Title:e.target.value})}/><input placeholder="Email" value={contactForm.Email} onChange={e=>setContactForm({...contactForm,Email:e.target.value})}/><input placeholder="Phone" value={contactForm.Phone} onChange={e=>setContactForm({...contactForm,Phone:e.target.value})}/><select value={contactForm.Vertical} onChange={e=>setContactForm({...contactForm,Vertical:e.target.value})}><option>Insurance</option><option>Real Estate</option><option>Commercial Broker</option><option>Property Management</option><option>Mortgage</option><option>Home Care</option></select><input placeholder="Market" value={contactForm.Market} onChange={e=>setContactForm({...contactForm,Market:e.target.value})}/></div><button onClick={()=>addContact()}>Save to Contacts Tab</button></div></div>}</div>
}
ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);